// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJA91fnffhAg2MomrMbL9Qu6LuPoaybI',
    appId: '1:381507930224:web:106dbcff6eed84d04c4cb5',
    messagingSenderId: '381507930224',
    projectId: 'control-financiero-app-b9f91',
    authDomain: 'control-financiero-app-b9f91.firebaseapp.com',
    storageBucket: 'control-financiero-app-b9f91.firebasestorage.app',
    measurementId: 'G-79VZMP46ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYw4vSA-wzhTrg1GMtrJmsqYGR--eAtg',
    appId: '1:381507930224:android:4c3fd14decdcb6164c4cb5',
    messagingSenderId: '381507930224',
    projectId: 'control-financiero-app-b9f91',
    storageBucket: 'control-financiero-app-b9f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCudKM5_b6t2jzUBVHh1mnuTAxLqXuTa1U',
    appId: '1:381507930224:ios:6b92b76966bacd6b4c4cb5',
    messagingSenderId: '381507930224',
    projectId: 'control-financiero-app-b9f91',
    storageBucket: 'control-financiero-app-b9f91.firebasestorage.app',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCudKM5_b6t2jzUBVHh1mnuTAxLqXuTa1U',
    appId: '1:381507930224:ios:6b92b76966bacd6b4c4cb5',
    messagingSenderId: '381507930224',
    projectId: 'control-financiero-app-b9f91',
    storageBucket: 'control-financiero-app-b9f91.firebasestorage.app',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyJA91fnffhAg2MomrMbL9Qu6LuPoaybI',
    appId: '1:381507930224:web:54e1b40c98da04954c4cb5',
    messagingSenderId: '381507930224',
    projectId: 'control-financiero-app-b9f91',
    authDomain: 'control-financiero-app-b9f91.firebaseapp.com',
    storageBucket: 'control-financiero-app-b9f91.firebasestorage.app',
    measurementId: 'G-E7CHZZTQGX',
  );
}
